import type { Club } from '@/lib/engine/types';

export const CLUBS: Club[] = [
  { id: 'boca', name: 'Boca Juniors', short: 'Boca', colors: ['#0a3a8c', '#f2c200'], league: 'ar-primera', size: 10, nickname: 'el Xeneize' },
  { id: 'river', name: 'River Plate', short: 'River', colors: ['#ffffff', '#d81e3f'], league: 'ar-primera', size: 10, nickname: 'el Millonario' },
  { id: 'racing', name: 'Racing Club', short: 'Racing', colors: ['#7ab8e6', '#ffffff'], league: 'ar-primera', size: 9, nickname: 'la Academia' },
  { id: 'independiente', name: 'Independiente', short: 'Independiente', colors: ['#d32f2f', '#ffffff'], league: 'ar-primera', size: 9, nickname: 'el Rojo' },
  { id: 'sanlorenzo', name: 'San Lorenzo', short: 'San Lorenzo', colors: ['#1b3f8b', '#c8102e'], league: 'ar-primera', size: 8, nickname: 'el Ciclón' },
  { id: 'velez', name: 'Vélez Sarsfield', short: 'Vélez', colors: ['#ffffff', '#0a4ea3'], league: 'ar-primera', size: 8, nickname: 'el Fortín' },
  { id: 'estudiantes', name: 'Estudiantes de La Plata', short: 'Estudiantes', colors: ['#e01e2b', '#ffffff'], league: 'ar-primera', size: 7, nickname: 'el Pincha' },
  { id: 'central', name: 'Rosario Central', short: 'Central', colors: ['#1a4fa0', '#f2c200'], league: 'ar-primera', size: 7, nickname: 'el Canalla' },
  { id: 'newells', name: "Newell's Old Boys", short: "Newell's", colors: ['#d3222a', '#000000'], league: 'ar-primera', size: 7, nickname: 'la Lepra' },
  { id: 'talleres', name: 'Talleres', short: 'Talleres', colors: ['#1b4fa0', '#ffffff'], league: 'ar-primera', size: 7, nickname: 'la T' },
  { id: 'belgrano', name: 'Belgrano', short: 'Belgrano', colors: ['#7ab8e6', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Pirata' },
  { id: 'lanus', name: 'Lanús', short: 'Lanús', colors: ['#7b1f2b', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Granate' },
  { id: 'huracan', name: 'Huracán', short: 'Huracán', colors: ['#ffffff', '#d81e3f'], league: 'ar-primera', size: 6, nickname: 'el Globo' },
  { id: 'argentinos', name: 'Argentinos Juniors', short: 'Argentinos', colors: ['#d81e3f', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Bicho' },
  { id: 'gimnasia', name: 'Gimnasia y Esgrima La Plata', short: 'Gimnasia', colors: ['#1d5fa8', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Lobo' },
  { id: 'colon', name: 'Colón', short: 'Colón', colors: ['#d3222a', '#000000'], league: 'ar-primera', size: 6, nickname: 'el Sabalero' },
  { id: 'banfield', name: 'Banfield', short: 'Banfield', colors: ['#1a6b3c', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Taladro' },
  { id: 'defensa', name: 'Defensa y Justicia', short: 'Defensa', colors: ['#f2c200', '#1a6b3c'], league: 'ar-primera', size: 5, nickname: 'el Halcón' },
  { id: 'godoycruz', name: 'Godoy Cruz', short: 'Godoy Cruz', colors: ['#1a4fa0', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Tomba' },
  { id: 'instituto', name: 'Instituto', short: 'Instituto', colors: ['#d3222a', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'la Gloria' },
  { id: 'union', name: 'Unión', short: 'Unión', colors: ['#d3222a', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Tatengue' },
  { id: 'atltucuman', name: 'Atlético Tucumán', short: 'Atl. Tucumán', colors: ['#7ab8e6', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Decano' },
  { id: 'tigre', name: 'Tigre', short: 'Tigre', colors: ['#1a4fa0', '#d81e3f'], league: 'ar-primera', size: 4, nickname: 'el Matador' },
  { id: 'sarmiento', name: 'Sarmiento', short: 'Sarmiento', colors: ['#1a6b3c', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'el Verde' },
  { id: 'platense', name: 'Platense', short: 'Platense', colors: ['#7b3f1f', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'el Calamar' },
  { id: 'centralcordoba', name: 'Central Córdoba', short: 'C. Córdoba', colors: ['#000000', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'el Ferroviario' },
  { id: 'indriv', name: 'Independiente Rivadavia', short: 'Ind. Rivadavia', colors: ['#1a4fa0', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'la Lepra mendocina' },
  { id: 'aldosivi', name: 'Aldosivi', short: 'Aldosivi', colors: ['#f2c200', '#1a6b3c'], league: 'ar-primera', size: 3, nickname: 'el Tiburón' },
  { id: 'barracas', name: 'Barracas Central', short: 'Barracas', colors: ['#d3222a', '#ffffff'], league: 'ar-primera', size: 3, nickname: 'el Guapo' },
  { id: 'riestra', name: 'Deportivo Riestra', short: 'Riestra', colors: ['#000000', '#f2c200'], league: 'ar-primera', size: 3, nickname: 'el Blanquinegro' },

  { id: 'quilmes', name: 'Quilmes', short: 'Quilmes', colors: ['#ffffff', '#1a4fa0'], league: 'ar-nacional', size: 6, nickname: 'el Cervecero' },
  { id: 'ferro', name: 'Ferro Carril Oeste', short: 'Ferro', colors: ['#1a6b3c', '#ffffff'], league: 'ar-nacional', size: 5, nickname: 'el Verdolaga' },
  { id: 'chacarita', name: 'Chacarita Juniors', short: 'Chacarita', colors: ['#d3222a', '#000000'], league: 'ar-nacional', size: 5, nickname: 'el Funebrero' },
  { id: 'sanmartint', name: 'San Martín de Tucumán', short: 'San Martín (T)', colors: ['#d3222a', '#ffffff'], league: 'ar-nacional', size: 5, nickname: 'el Santo' },
  { id: 'atlanta', name: 'Atlanta', short: 'Atlanta', colors: ['#f2c200', '#1a4fa0'], league: 'ar-nacional', size: 4, nickname: 'el Bohemio' },
  { id: 'allboys', name: 'All Boys', short: 'All Boys', colors: ['#ffffff', '#000000'], league: 'ar-nacional', size: 4, nickname: 'el Albo' },
  { id: 'chicago', name: 'Nueva Chicago', short: 'Chicago', colors: ['#1a6b3c', '#000000'], league: 'ar-nacional', size: 4, nickname: 'el Torito' },
  { id: 'almagro', name: 'Almagro', short: 'Almagro', colors: ['#1a4fa0', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Tricolor' },
  { id: 'temperley', name: 'Temperley', short: 'Temperley', colors: ['#7ab8e6', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Gasolero' },
  { id: 'moron', name: 'Deportivo Morón', short: 'Morón', colors: ['#d3222a', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Gallo' },
  { id: 'gimnasiam', name: 'Gimnasia y Esgrima de Mendoza', short: 'Gimnasia (M)', colors: ['#ffffff', '#1a4fa0'], league: 'ar-nacional', size: 4, nickname: 'el Lobo mendocino' },
  { id: 'santelmo', name: 'San Telmo', short: 'San Telmo', colors: ['#1a4fa0', '#f2c200'], league: 'ar-nacional', size: 2, nickname: 'el Candombero' },
  { id: 'defbelgrano', name: 'Defensores de Belgrano', short: 'Defensores', colors: ['#d3222a', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Dragón' },
  { id: 'racingcba', name: 'Racing de Córdoba', short: 'Racing (C)', colors: ['#7ab8e6', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'la Academia cordobesa' },
  { id: 'estudiantesrc', name: 'Estudiantes de Río Cuarto', short: 'Estudiantes (RC)', colors: ['#1a6b3c', '#ffffff'], league: 'ar-nacional', size: 3 },
  { id: 'agropecuario', name: 'Agropecuario', short: 'Agropecuario', colors: ['#1a6b3c', '#ffffff'], league: 'ar-nacional', size: 2, nickname: 'el Sojero' },
  { id: 'guemes', name: 'Güemes', short: 'Güemes', colors: ['#000000', '#ffffff'], league: 'ar-nacional', size: 2, nickname: 'el Gaucho' },
  { id: 'mitre', name: 'Mitre', short: 'Mitre', colors: ['#f2c200', '#000000'], league: 'ar-nacional', size: 2, nickname: 'el Aurinegro' },

  { id: 'losandes', name: 'Los Andes', short: 'Los Andes', colors: ['#d3222a', '#ffffff'], league: 'ar-b', size: 3, nickname: 'el Milrayitas' },
  { id: 'colegiales', name: 'Colegiales', short: 'Colegiales', colors: ['#ffffff', '#000000'], league: 'ar-b', size: 2, nickname: 'el Tricolor de Munro' },
  { id: 'acassuso', name: 'Acassuso', short: 'Acassuso', colors: ['#d3222a', '#1a4fa0'], league: 'ar-b', size: 1, nickname: 'el Quemero de Boulogne' },
  { id: 'comunicaciones', name: 'Comunicaciones', short: 'Comunicaciones', colors: ['#1a6b3c', '#ffffff'], league: 'ar-b', size: 2, nickname: 'el Cartero' },
  { id: 'tallerresre', name: 'Talleres de Remedios de Escalada', short: 'Talleres (RE)', colors: ['#d3222a', '#ffffff'], league: 'ar-b', size: 2, nickname: 'el Albirrojo' },
  { id: 'canuelas', name: 'Cañuelas', short: 'Cañuelas', colors: ['#7b1f2b', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Tambero' },
  { id: 'docksud', name: 'Sportivo Dock Sud', short: 'Dock Sud', colors: ['#1a4fa0', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Docke' },
  { id: 'fenix', name: 'Fénix', short: 'Fénix', colors: ['#7b3f8b', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Ave' },
  { id: 'sanmiguel', name: 'San Miguel', short: 'San Miguel', colors: ['#f2c200', '#d3222a'], league: 'ar-b', size: 2, nickname: 'el Trueno Verde' },
  { id: 'excursionistas', name: 'Excursionistas', short: 'Excursionistas', colors: ['#ffffff', '#1a4fa0'], league: 'ar-b', size: 2, nickname: 'el Villero' },
  { id: 'uaiurquiza', name: 'UAI Urquiza', short: 'UAI Urquiza', colors: ['#1a6b3c', '#ffffff'], league: 'ar-b', size: 1 },
  { id: 'armenio', name: 'Deportivo Armenio', short: 'Armenio', colors: ['#d3222a', '#1a4fa0'], league: 'ar-b', size: 1, nickname: 'el Tricolor' },
  { id: 'italiano', name: 'Sportivo Italiano', short: 'Italiano', colors: ['#1a4fa0', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Tano' },
  { id: 'espanol', name: 'Deportivo Español', short: 'Español', colors: ['#d3222a', '#f2c200'], league: 'ar-b', size: 2, nickname: 'el Gallego' },
  { id: 'argentinoq', name: 'Argentino de Quilmes', short: 'Argentino (Q)', colors: ['#1a6b3c', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Mate' },
  { id: 'ituzaingo', name: 'Ituzaingó', short: 'Ituzaingó', colors: ['#1a4fa0', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Verde' },

  { id: 'penarol', name: 'Peñarol', short: 'Peñarol', colors: ['#000000', '#f2c200'], league: 'uy-primera', size: 8, nickname: 'el Carbonero' },
  { id: 'nacional', name: 'Nacional', short: 'Nacional', colors: ['#ffffff', '#1a4fa0'], league: 'uy-primera', size: 8, nickname: 'el Bolso' },
  { id: 'danubio', name: 'Danubio', short: 'Danubio', colors: ['#ffffff', '#000000'], league: 'uy-primera', size: 7, nickname: 'la Franja' },
  { id: 'defensor', name: 'Defensor Sporting', short: 'Defensor', colors: ['#7b3f8b', '#ffffff'], league: 'uy-primera', size: 7, nickname: 'el Violeta' },
  { id: 'liverpool', name: 'Liverpool', short: 'Liverpool', colors: ['#000000', '#1a4fa0'], league: 'uy-primera', size: 6, nickname: 'el Negriazul' },
  { id: 'wanderers', name: 'Montevideo Wanderers', short: 'Wanderers', colors: ['#000000', '#ffffff'], league: 'uy-primera', size: 6, nickname: 'el Bohemio' },
  { id: 'racinguy', name: 'Racing', short: 'Racing (Uy)', colors: ['#1a6b3c', '#ffffff'], league: 'uy-primera', size: 6, nickname: 'el Cervecero' },
  { id: 'progreso', name: 'Progreso', short: 'Progreso', colors: ['#f2c200', '#d3222a'], league: 'uy-primera', size: 5, nickname: 'el Gaucho' },
  { id: 'cerro', name: 'Cerro', short: 'Cerro', colors: ['#ffffff', '#7ab8e6'], league: 'uy-primera', size: 5, nickname: 'el Villero' },
  { id: 'bostonriver', name: 'Boston River', short: 'Boston River', colors: ['#1a6b3c', '#d3222a'], league: 'uy-primera', size: 5, nickname: 'el Sastre' },
  { id: 'cerrolargo', name: 'Cerro Largo', short: 'Cerro Largo', colors: ['#1a4fa0', '#ffffff'], league: 'uy-primera', size: 4, nickname: 'el Arachán' },
  { id: 'maldonado', name: 'Deportivo Maldonado', short: 'Maldonado', colors: ['#d3222a', '#1a6b3c'], league: 'uy-primera', size: 4, nickname: 'el Depo' },
  { id: 'citytorque', name: 'Montevideo City Torque', short: 'City Torque', colors: ['#7ab8e6', '#ffffff'], league: 'uy-primera', size: 4, nickname: 'el Ciudadano' },
  { id: 'centralespanol', name: 'Central Español', short: 'Central Español', colors: ['#d3222a', '#1a4fa0'], league: 'uy-primera', size: 4, nickname: 'el Palermitano' },
  { id: 'albion', name: 'Albion', short: 'Albion', colors: ['#d3222a', '#0a3a8c'], league: 'uy-primera', size: 3, nickname: 'el Decano' },
  { id: 'juventud', name: 'Juventud', short: 'Juventud', colors: ['#1a4fa0', '#ffffff'], league: 'uy-primera', size: 3, nickname: 'el Canario' },

  { id: 'riverplateuy', name: 'River Plate', short: 'River Plate (Uy)', colors: ['#d3222a', '#ffffff'], league: 'uy-segunda', size: 2, nickname: 'el Darsenero' },
  { id: 'rentistas', name: 'Rentistas', short: 'Rentistas', colors: ['#d3222a', '#000000'], league: 'uy-segunda', size: 2, nickname: 'el Bicho' },
  { id: 'miramar', name: 'Miramar Misiones', short: 'Miramar', colors: ['#000000', '#ffffff'], league: 'uy-segunda', size: 2, nickname: 'el Cebra' },
  { id: 'plazacolonia', name: 'Plaza Colonia', short: 'Plaza Colonia', colors: ['#ffffff', '#1a6b3c'], league: 'uy-segunda', size: 2, nickname: 'las Patas Blancas' },
  { id: 'tacuarembo', name: 'Tacuarembó', short: 'Tacuarembó', colors: ['#7b1f2b', '#ffffff'], league: 'uy-segunda', size: 2, nickname: 'el Tacua' },
  { id: 'huracanuy', name: 'Huracán', short: 'Huracán (Uy)', colors: ['#1a4fa0', '#ffffff'], league: 'uy-segunda', size: 1, nickname: 'el Hura' },
  { id: 'paysandu', name: 'Paysandú', short: 'Paysandú', colors: ['#ffffff', '#1a4fa0'], league: 'uy-segunda', size: 2, nickname: 'el Paysa' },
  { id: 'colonuy', name: 'Colón', short: 'Colón (Uy)', colors: ['#1a6b3c', '#d3222a'], league: 'uy-segunda', size: 1, nickname: 'el Verde' },
  { id: 'cerrito', name: 'Cerrito', short: 'Cerrito', colors: ['#f2c200', '#1a6b3c'], league: 'uy-segunda', size: 1, nickname: 'el Auriverde' },
  { id: 'umontevideo', name: 'Uruguay Montevideo', short: 'Uruguay MVD', colors: ['#7ab8e6', '#000000'], league: 'uy-segunda', size: 1, nickname: 'la Celestina' },
  { id: 'atenas', name: 'Atenas', short: 'Atenas', colors: ['#1a4fa0', '#d3222a'], league: 'uy-segunda', size: 1, nickname: 'el Azulgrana' },
  { id: 'oriental', name: 'Oriental', short: 'Oriental', colors: ['#7ab8e6', '#ffffff'], league: 'uy-segunda', size: 1, nickname: 'el Paceño' },
  { id: 'laluz', name: 'La Luz', short: 'La Luz', colors: ['#1a6b3c', '#ffffff'], league: 'uy-segunda', size: 1, nickname: 'el Merengue' },

  { id: 'alianzalima', name: 'Alianza Lima', short: 'Alianza Lima', colors: ['#0a3a8c', '#ffffff'], league: 'pe-primera', size: 9, nickname: 'el Íntimo' },
  { id: 'universitario', name: 'Universitario de Deportes', short: 'Universitario', colors: ['#e8d9a8', '#7b1f2b'], league: 'pe-primera', size: 9, nickname: 'la U' },
  { id: 'sportingcristal', name: 'Sporting Cristal', short: 'Cristal', colors: ['#7ab8e6', '#ffffff'], league: 'pe-primera', size: 9, nickname: 'el Cervecero' },
  { id: 'melgar', name: 'FBC Melgar', short: 'Melgar', colors: ['#d3222a', '#000000'], league: 'pe-primera', size: 7, nickname: 'el Dominó' },
  { id: 'cienciano', name: 'Cienciano', short: 'Cienciano', colors: ['#d3222a', '#ffffff'], league: 'pe-primera', size: 7, nickname: 'el Papá' },
  { id: 'sportboys', name: 'Sport Boys', short: 'Sport Boys', colors: ['#e88fb3', '#1a4fa0'], league: 'pe-primera', size: 6, nickname: 'la Misilera' },
  { id: 'cuscofc', name: 'Cusco FC', short: 'Cusco FC', colors: ['#c9a227', '#000000'], league: 'pe-primera', size: 6, nickname: 'el Dorado' },
  { id: 'garcilaso', name: 'Deportivo Garcilaso', short: 'Garcilaso', colors: ['#7ab8e6', '#ffffff'], league: 'pe-primera', size: 5, nickname: 'la G' },
  { id: 'sporthuancayo', name: 'Sport Huancayo', short: 'Sport Huancayo', colors: ['#d3222a', '#ffffff'], league: 'pe-primera', size: 5, nickname: 'el Rojo Matador' },
  { id: 'adt', name: 'ADT', short: 'ADT', colors: ['#7ab8e6', '#ffffff'], league: 'pe-primera', size: 5, nickname: 'el Vendaval Celeste' },
  { id: 'alianzaatletico', name: 'Alianza Atlético', short: 'Alianza Atlético', colors: ['#ffffff', '#1a4fa0'], league: 'pe-primera', size: 4, nickname: 'Alianza de Oro' },
  { id: 'atleticograu', name: 'Atlético Grau', short: 'Grau', colors: ['#ffffff', '#d3222a'], league: 'pe-primera', size: 4, nickname: 'los Albos' },
  { id: 'comerciantesunidos', name: 'Comerciantes Unidos', short: 'Comerciantes Unidos', colors: ['#7b3f8b', '#f2c200'], league: 'pe-primera', size: 4, nickname: 'las Águilas' },
  { id: 'utc', name: 'UTC', short: 'UTC', colors: ['#e8d9a8', '#5c3a21'], league: 'pe-primera', size: 4, nickname: 'el Gavilán' },
  { id: 'cajamarca', name: 'FC Cajamarca', short: 'Cajamarca', colors: ['#1a4fa0', '#f2c200'], league: 'pe-primera', size: 3 },
  { id: 'moquegua', name: 'Deportivo Moquegua', short: 'Moquegua', colors: ['#f2c200', '#000000'], league: 'pe-primera', size: 3 },
  { id: 'loschankas', name: 'Los Chankas', short: 'Los Chankas', colors: ['#7b1f2b', '#d9782d'], league: 'pe-primera', size: 3, nickname: 'los Guerreros' },
  { id: 'jpiicollege', name: 'Juan Pablo II College', short: 'JP II College', colors: ['#ffffff', '#f2c200'], league: 'pe-primera', size: 2 },

  { id: 'cantolao', name: 'Academia Cantolao', short: 'Cantolao', colors: ['#f2c200', '#000000'], league: 'pe-segunda', size: 2, nickname: 'el Delfín' },
  { id: 'adajaen', name: 'ADA Jaén', short: 'ADA Jaén', colors: ['#1a6b3c', '#f2c200'], league: 'pe-segunda', size: 1 },
  { id: 'alianzauniversidad', name: 'Alianza Universidad', short: 'Alianza Universidad', colors: ['#1a4fa0', '#d3222a'], league: 'pe-segunda', size: 3, nickname: 'la UDH' },
  { id: 'ayacucho', name: 'Ayacucho FC', short: 'Ayacucho FC', colors: ['#ffffff', '#d9782d'], league: 'pe-segunda', size: 3, nickname: 'los Zorros' },
  { id: 'tacnaheroica', name: 'Bentín Tacna Heroica', short: 'Tacna Heroica', colors: ['#1a4fa0', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'el Vendaval Azul' },
  { id: 'mannucci', name: 'Carlos A. Mannucci', short: 'Mannucci', colors: ['#0a3a8c', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'el Grifo' },
  { id: 'comerciantesfc', name: 'Comerciantes FC', short: 'Comerciantes FC', colors: ['#1a6b3c', '#ffffff'], league: 'pe-segunda', size: 1, nickname: 'la Fuerza' },
  { id: 'binacional', name: 'Deportivo Binacional', short: 'Binacional', colors: ['#7ab8e6', '#ffffff'], league: 'pe-segunda', size: 3, nickname: 'el Poderoso' },
  { id: 'llacuabamba', name: 'Deportivo Llacuabamba', short: 'Llacuabamba', colors: ['#ffffff', '#2fa89e'], league: 'pe-segunda', size: 1, nickname: 'los Mineros' },
  { id: 'cni', name: 'Estudiantil CNI', short: 'CNI', colors: ['#ffffff', '#1a6b3c'], league: 'pe-segunda', size: 1 },
  { id: 'piratafc', name: 'Pirata FC', short: 'Pirata FC', colors: ['#000000', '#1a6b3c'], league: 'pe-segunda', size: 2, nickname: 'los Piratas' },
  { id: 'santosnazca', name: 'Santos FC', short: 'Santos (Nazca)', colors: ['#1a4fa0', '#ffffff'], league: 'pe-segunda', size: 1, nickname: 'la Máquina' },
  { id: 'unioncomercio', name: 'Unión Comercio', short: 'Unión Comercio', colors: ['#d3222a', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'el Poderoso del Altomayo' },
  { id: 'unionminas', name: 'Unión Minas', short: 'Unión Minas', colors: ['#f2c200', '#1a4fa0'], league: 'pe-segunda', size: 1, nickname: 'el Rodillo Minero' },
  { id: 'ucv', name: 'Universidad César Vallejo', short: 'UCV', colors: ['#1a4fa0', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'los Poetas' },
  { id: 'usmp', name: 'Universidad San Martín', short: 'USMP', colors: ['#ffffff', '#0a3a8c'], league: 'pe-segunda', size: 2, nickname: 'el Sanmartinense' },

  { id: 'atlnacional', name: 'Atlético Nacional', short: 'Nacional (Col)', colors: ['#1a6b3c', '#ffffff'], league: 'co-primera', size: 9, nickname: 'el Verdolaga' },
  { id: 'millonarios', name: 'Millonarios', short: 'Millonarios', colors: ['#1a4fa0', '#ffffff'], league: 'co-primera', size: 9, nickname: 'el Embajador' },
  { id: 'americacali', name: 'América de Cali', short: 'América de Cali', colors: ['#d3222a', '#ffffff'], league: 'co-primera', size: 8, nickname: 'los Diablos Rojos' },
  { id: 'santafe', name: 'Independiente Santa Fe', short: 'Santa Fe', colors: ['#c8102e', '#ffffff'], league: 'co-primera', size: 8, nickname: 'el Expreso Rojo' },
  { id: 'medellin', name: 'Independiente Medellín', short: 'Medellín', colors: ['#d32f2f', '#0a3a8c'], league: 'co-primera', size: 8, nickname: 'el Poderoso' },
  { id: 'junior', name: 'Junior de Barranquilla', short: 'Junior', colors: ['#d3222a', '#0a3a8c'], league: 'co-primera', size: 7, nickname: 'el Tiburón' },
  { id: 'cali', name: 'Deportivo Cali', short: 'Deportivo Cali', colors: ['#1a6b3c', '#d3222a'], league: 'co-primera', size: 7, nickname: 'los Azucareros' },
  { id: 'oncecaldas', name: 'Once Caldas', short: 'Once Caldas', colors: ['#ffffff', '#1a6b3c'], league: 'co-primera', size: 6, nickname: 'el Álbum' },
  { id: 'tolima', name: 'Deportes Tolima', short: 'Tolima', colors: ['#7b1f2b', '#f2c200'], league: 'co-primera', size: 6, nickname: 'los Pijaos' },
  { id: 'bucaramanga', name: 'Atlético Bucaramanga', short: 'Bucaramanga', colors: ['#f2c200', '#1a6b3c'], league: 'co-primera', size: 6, nickname: 'los Leopardos' },
  { id: 'pereira', name: 'Deportivo Pereira', short: 'Pereira', colors: ['#d3222a', '#f2c200'], league: 'co-primera', size: 5, nickname: 'el Matecaña' },
  { id: 'pasto', name: 'Deportivo Pasto', short: 'Pasto', colors: ['#d3222a', '#1a4fa0'], league: 'co-primera', size: 5, nickname: 'los Volcánicos' },
  { id: 'aguilasdoradas', name: 'Águilas Doradas', short: 'Águilas Doradas', colors: ['#c9a227', '#000000'], league: 'co-primera', size: 4 },
  { id: 'cucuta', name: 'Cúcuta Deportivo', short: 'Cúcuta', colors: ['#d3222a', '#000000'], league: 'co-primera', size: 4, nickname: 'los Motilones' },
  { id: 'jaguares', name: 'Jaguares de Córdoba', short: 'Jaguares', colors: ['#7ab8e6', '#ffffff'], league: 'co-primera', size: 4, nickname: 'las Fieras del Sinú' },
  { id: 'boyacachico', name: 'Boyacá Chicó', short: 'Boyacá Chicó', colors: ['#000000', '#ffffff'], league: 'co-primera', size: 3, nickname: 'el Ajedrezado' },
  { id: 'llaneros', name: 'Llaneros FC', short: 'Llaneros', colors: ['#ffffff', '#000000'], league: 'co-primera', size: 3, nickname: 'los Centauros' },
  { id: 'fortaleza', name: 'Fortaleza FC', short: 'Fortaleza', colors: ['#0a3a8c', '#7b1f2b'], league: 'co-primera', size: 3 },
  { id: 'interbogota', name: 'Internacional de Bogotá', short: 'Inter de Bogotá', colors: ['#ffffff', '#f2c200'], league: 'co-primera', size: 3 },
  { id: 'alianzavalledupar', name: 'Alianza Valledupar', short: 'Alianza Valledupar', colors: ['#0a3a8c', '#ffffff'], league: 'co-primera', size: 2, nickname: 'los Vallenatos' },

  { id: 'envigado', name: 'Envigado FC', short: 'Envigado', colors: ['#d9782d', '#1a6b3c'], league: 'co-segunda', size: 3, nickname: 'la Naranja Mecánica' },
  { id: 'unionmagdalena', name: 'Unión Magdalena', short: 'Unión Magdalena', colors: ['#d3222a', '#1a4fa0'], league: 'co-segunda', size: 2, nickname: 'el Ciclón Bananero' },
  { id: 'quindio', name: 'Deportes Quindío', short: 'Quindío', colors: ['#1a6b3c', '#f2c200'], league: 'co-segunda', size: 2, nickname: 'los Cuyabros' },
  { id: 'patriotas', name: 'Patriotas', short: 'Patriotas', colors: ['#d3222a', '#1a6b3c'], league: 'co-segunda', size: 2, nickname: 'el Lancero' },
  { id: 'realcartagena', name: 'Real Cartagena', short: 'Real Cartagena', colors: ['#f2c200', '#1a6b3c'], league: 'co-segunda', size: 2, nickname: 'el Equipo Heroico' },
  { id: 'realsantander', name: 'Real Santander', short: 'Real Santander', colors: ['#ffffff', '#7ab8e6'], league: 'co-segunda', size: 2, nickname: 'los Albicelestes' },
  { id: 'itaguileones', name: 'Itagüí Leones', short: 'Itagüí', colors: ['#f2c200', '#1a6b3c'], league: 'co-segunda', size: 1, nickname: 'los Felinos' },
  { id: 'tigresfc', name: 'Tigres FC', short: 'Tigres', colors: ['#6b6b6b', '#c9a876'], league: 'co-segunda', size: 1 },
  { id: 'bogotafc', name: 'Bogotá FC', short: 'Bogotá FC', colors: ['#f2c200', '#d3222a'], league: 'co-segunda', size: 1, nickname: 'los Bogotanos' },
  { id: 'barranquillafc', name: 'Barranquilla FC', short: 'Barranquilla FC', colors: ['#1a6b3c', '#f2c200'], league: 'co-segunda', size: 1, nickname: 'los Rojos de Curramba' },
  { id: 'bocacali', name: 'Boca Juniors de Cali', short: 'Boca de Cali', colors: ['#1a4fa0', '#f2c200'], league: 'co-segunda', size: 1, nickname: 'la Ciencia Boquense' },
  { id: 'atleticofc', name: 'Atlético FC', short: 'Atlético FC', colors: ['#0a3a8c', '#f2c200'], league: 'co-segunda', size: 1 },
  { id: 'realcundinamarca', name: 'Real Cundinamarca', short: 'Real Cundinamarca', colors: ['#1a6b3c', '#f2c200'], league: 'co-segunda', size: 1 },
  { id: 'vallecauca', name: 'Independiente Valle del Cauca', short: 'Valle del Cauca', colors: ['#1a6b3c', '#ffffff'], league: 'co-segunda', size: 1 },
  { id: 'interpalmira', name: 'Inter de Palmira', short: 'Inter de Palmira', colors: ['#1a4fa0', '#1a6b3c'], league: 'co-segunda', size: 1 },
  { id: 'orsomarso', name: 'Orsomarso', short: 'Orsomarso', colors: ['#1a6b3c', '#ffffff'], league: 'co-segunda', size: 1 },
  { id: 'colocolo', name: 'Colo-Colo', short: 'Colo-Colo', colors: ['#000000', '#ffffff'], league: 'cl-primera', size: 9, nickname: 'el Cacique' },
  { id: 'udechile', name: 'Universidad de Chile', short: 'U. de Chile', colors: ['#0033a0', '#000000'], league: 'cl-primera', size: 9, nickname: 'la U' },
  { id: 'ucatolica', name: 'Universidad Católica', short: 'U. Católica', colors: ['#0033a0', '#ffffff'], league: 'cl-primera', size: 8, nickname: 'los Cruzados' },
  { id: 'everton', name: 'Everton', short: 'Everton', colors: ['#0033a0', '#f2c200'], league: 'cl-primera', size: 6, nickname: 'los Ruleteros' },
  { id: 'coquimbounido', name: 'Coquimbo Unido', short: 'Coquimbo Unido', colors: ['#f2c200', '#000000'], league: 'cl-primera', size: 6, nickname: 'los Piratas' },
  { id: 'ohiggins', name: "O'Higgins", short: "O'Higgins", colors: ['#7ab8e6', '#ffffff'], league: 'cl-primera', size: 5, nickname: 'la Capo de Provincia' },
  { id: 'huachipato', name: 'Huachipato', short: 'Huachipato', colors: ['#0a3a8c', '#000000'], league: 'cl-primera', size: 5, nickname: 'los Acereros' },
  { id: 'cobresal', name: 'Cobresal', short: 'Cobresal', colors: ['#ffffff', '#000000'], league: 'cl-primera', size: 5, nickname: 'los Mineros' },
  { id: 'audaxitaliano', name: 'Audax Italiano', short: 'Audax Italiano', colors: ['#0a8a3c', '#ffffff'], league: 'cl-primera', size: 4, nickname: 'los Itálicos' },
  { id: 'palestino', name: 'Palestino', short: 'Palestino', colors: ['#ce1126', '#007a3d'], league: 'cl-primera', size: 4, nickname: 'los Árabes' },
  { id: 'unioncalera', name: 'Unión La Calera', short: 'La Calera', colors: ['#d3222a', '#ffffff'], league: 'cl-primera', size: 4, nickname: 'los Cementeros' },
  { id: 'nublense', name: 'Ñublense', short: 'Ñublense', colors: ['#d3222a', '#000000'], league: 'cl-primera', size: 4, nickname: 'los Diablos Rojos' },
  { id: 'laserena', name: 'Deportes La Serena', short: 'La Serena', colors: ['#7b1f2b', '#ffffff'], league: 'cl-primera', size: 3, nickname: 'los Papayeros' },
  { id: 'limache', name: 'Deportes Limache', short: 'Limache', colors: ['#d3222a', '#000000'], league: 'cl-primera', size: 3, nickname: 'los Tomateros' },
  { id: 'deportesconcepcion', name: 'Deportes Concepción', short: 'Deportes Concepción', colors: ['#7b3f8b', '#ffffff'], league: 'cl-primera', size: 2, nickname: 'el León de Collao' },
  { id: 'udeconcepcion', name: 'Universidad de Concepción', short: 'U. de Concepción', colors: ['#1a4fa0', '#f2c200'], league: 'cl-primera', size: 2, nickname: 'el Campanil' },
  { id: 'cobreloa', name: 'Cobreloa', short: 'Cobreloa', colors: ['#d9782d', '#000000'], league: 'cl-segunda', size: 3, nickname: 'los Loínos' },
  { id: 'unionespanola', name: 'Unión Española', short: 'Unión Española', colors: ['#d3222a', '#f2c200'], league: 'cl-segunda', size: 3, nickname: 'la Furia' },
  { id: 'santiagowanderers', name: 'Santiago Wanderers', short: 'Wanderers', colors: ['#1a6b3c', '#ffffff'], league: 'cl-segunda', size: 3, nickname: 'los Caturros' },
  { id: 'iquique', name: 'Deportes Iquique', short: 'Iquique', colors: ['#7ab8e6', '#000000'], league: 'cl-segunda', size: 2, nickname: 'los Dragones Celestes' },
  { id: 'magallanes', name: 'Magallanes', short: 'Magallanes', colors: ['#ffffff', '#7ab8e6'], league: 'cl-segunda', size: 2, nickname: 'la Academia' },
  { id: 'copiapo', name: 'Deportes Copiapó', short: 'Copiapó', colors: ['#ffffff', '#d3222a'], league: 'cl-segunda', size: 2, nickname: 'el León de Atacama' },
  { id: 'antofagasta', name: 'Deportes Antofagasta', short: 'Antofagasta', colors: ['#7ab8e6', '#000000'], league: 'cl-segunda', size: 2, nickname: 'los Pumas' },
  { id: 'sanmarcos', name: 'San Marcos de Arica', short: 'San Marcos', colors: ['#7ab8e6', '#ffffff'], league: 'cl-segunda', size: 1, nickname: 'los Bravos del Morro' },
  { id: 'sanluis', name: 'San Luis de Quillota', short: 'San Luis', colors: ['#f2c200', '#1a4fa0'], league: 'cl-segunda', size: 1, nickname: 'los Canarios' },
  { id: 'sanfelipe', name: 'Unión San Felipe', short: 'San Felipe', colors: ['#d3222a', '#ffffff'], league: 'cl-segunda', size: 1, nickname: 'los Uní Uní' },
  { id: 'curicounido', name: 'Curicó Unido', short: 'Curicó Unido', colors: ['#d3222a', '#ffffff'], league: 'cl-segunda', size: 1, nickname: 'los Torteros' },
  { id: 'rangerstalca', name: 'Rangers', short: 'Rangers (Talca)', colors: ['#d3222a', '#000000'], league: 'cl-segunda', size: 1, nickname: 'los Piducanos' },
  { id: 'temuco', name: 'Deportes Temuco', short: 'Temuco', colors: ['#ffffff', '#1a6b3c'], league: 'cl-segunda', size: 1, nickname: 'el León de Ñielol' },
  { id: 'recoleta', name: 'Deportes Recoleta', short: 'Recoleta', colors: ['#ffffff', '#1a4fa0'], league: 'cl-segunda', size: 1, nickname: 'los Albiazules' },
  { id: 'santacruz', name: 'Deportes Santa Cruz', short: 'Santa Cruz', colors: ['#ffffff', '#7b1f2b'], league: 'cl-segunda', size: 1, nickname: 'los Santacruzanos' },
  { id: 'puertomontt', name: 'Deportes Puerto Montt', short: 'Puerto Montt', colors: ['#ffffff', '#1a4fa0'], league: 'cl-segunda', size: 1, nickname: 'los Delfines' },
  { id: 'olimpia', name: 'Olimpia', short: 'Olimpia', colors: ['#000000', '#ffffff'], league: 'py-primera', size: 9, nickname: 'el Decano' },
  { id: 'cerroporteno', name: 'Cerro Porteño', short: 'Cerro Porteño', colors: ['#1a4fa0', '#c8102e'], league: 'py-primera', size: 9, nickname: 'el Ciclón' },
  { id: 'libertad', name: 'Libertad', short: 'Libertad', colors: ['#ffffff', '#000000'], league: 'py-primera', size: 8, nickname: 'el Gumarelo' },
  { id: 'guarani', name: 'Guaraní', short: 'Guaraní', colors: ['#000000', '#f2c200'], league: 'py-primera', size: 6, nickname: 'el Cacique' },
  { id: 'nacionalpy', name: 'Club Nacional', short: 'Nacional', colors: ['#d3222a', '#1a4fa0'], league: 'py-primera', size: 5, nickname: 'el Tricolor' },
  { id: 'luqueno', name: 'Sportivo Luqueño', short: 'Luqueño', colors: ['#1a4fa0', '#f2c200'], league: 'py-primera', size: 4, nickname: 'el Auriazul' },
  { id: 'dosdemayo', name: 'Sportivo 2 de Mayo', short: '2 de Mayo', colors: ['#ffffff', '#1a4fa0'], league: 'py-primera', size: 4, nickname: 'el Gallo Norteño' },
  { id: 'recoletapy', name: 'Deportivo Recoleta', short: 'Recoleta', colors: ['#f2c200', '#000000'], league: 'py-primera', size: 4, nickname: 'el Funebrero' },
  { id: 'trinidense', name: 'Sportivo Trinidense', short: 'Trinidense', colors: ['#1a4fa0', '#f2c200'], league: 'py-primera', size: 3, nickname: 'el Triqui' },
  { id: 'ameliano', name: 'Sportivo Ameliano', short: 'Ameliano', colors: ['#ffffff', '#1a4fa0'], league: 'py-primera', size: 3, nickname: 'la V Azulada' },
  { id: 'sanlorenzopy', name: 'Sportivo San Lorenzo', short: 'San Lorenzo', colors: ['#d3222a', '#ffffff'], league: 'py-primera', size: 2, nickname: 'el Rayadito' },
  { id: 'rubionu', name: 'Rubio Ñu', short: 'Rubio Ñu', colors: ['#ffffff', '#1a6b3c'], league: 'py-primera', size: 2, nickname: 'los Ñuenses' },
  { id: 'solamerica', name: 'Sol de América', short: 'Sol de América', colors: ['#1a4fa0', '#ffffff'], league: 'py-segunda', size: 3, nickname: 'los Dragones Azules' },
  { id: 'tacuary', name: 'Tacuary FBC', short: 'Tacuary', colors: ['#000000', '#ffffff'], league: 'py-segunda', size: 3, nickname: 'los Linces' },
  { id: 'santani', name: 'Deportivo Santaní', short: 'Santaní', colors: ['#000000', '#ffffff'], league: 'py-segunda', size: 2, nickname: 'la Albinegra' },
  { id: 'guairena', name: 'Guaireña FC', short: 'Guaireña', colors: ['#ffffff', '#7ab8e6'], league: 'py-segunda', size: 2, nickname: 'el Más Grande del Interior' },
  { id: 'generalcaballero', name: 'General Caballero JLM', short: 'Gral. Caballero', colors: ['#d3222a', '#ffffff'], league: 'py-segunda', size: 2, nickname: 'el General del Este' },
  { id: 'fernandodelamora', name: 'Fernando de la Mora', short: 'Fernando de la Mora', colors: ['#d3222a', '#000000'], league: 'py-segunda', size: 2, nickname: 'el Matador' },
  { id: 'carapegua', name: 'Sportivo Carapeguá', short: 'Carapeguá', colors: ['#d3222a', '#ffffff'], league: 'py-segunda', size: 1, nickname: 'el Potro' },
  { id: 'tembetary', name: 'Atlético Tembetary', short: 'Tembetary', colors: ['#d3222a', '#1a6b3c'], league: 'py-segunda', size: 1, nickname: 'los Rojiverdes' },
  { id: 'capiata', name: 'Deportivo Capiatá', short: 'Capiatá', colors: ['#f2c200', '#1a4fa0'], league: 'py-segunda', size: 1, nickname: 'los Escoberos' },
  { id: 'independientefbc', name: 'Independiente FBC', short: 'Independiente FBC', colors: ['#d3222a', '#ffffff'], league: 'py-segunda', size: 1, nickname: 'el Campograndense' },
  { id: 'resistencia', name: 'Resistencia SC', short: 'Resistencia', colors: ['#d3222a', '#000000'], league: 'py-segunda', size: 1, nickname: 'el Triángulo Rojo' },
  { id: 'docedejunio', name: '12 de Junio', short: '12 de Junio', colors: ['#1a4fa0', '#f2c200'], league: 'py-segunda', size: 1, nickname: 'el León del Chaco' },
  { id: 'tresdenoviembre', name: '3 de Noviembre', short: '3 de Noviembre', colors: ['#ffffff', '#1a4fa0'], league: 'py-segunda', size: 1 },
  { id: 'benjaminaceval', name: 'Benjamín Aceval', short: 'Benjamín Aceval', colors: ['#ffffff', '#d3222a'], league: 'py-segunda', size: 2, nickname: 'el Decano Chaqueño' },
  { id: 'encarnacionfc', name: 'Encarnación FC', short: 'Encarnación FC', colors: ['#ffffff', '#d3222a'], league: 'py-segunda', size: 1, nickname: 'la Albirroja Encarnacena' },
  { id: 'paraguariac', name: 'Paraguarí AC', short: 'Paraguarí', colors: ['#d3222a', '#ffffff'], league: 'py-segunda', size: 1 },
  { id: 'bolivar', name: 'Club Bolívar', short: 'Bolívar', colors: ['#7ab8e6', '#ffffff'], league: 'bo-primera', size: 9, nickname: 'la Academia' },
  { id: 'thestrongest', name: 'The Strongest', short: 'The Strongest', colors: ['#f2c200', '#000000'], league: 'bo-primera', size: 9, nickname: 'el Tigre' },
  { id: 'alwaysready', name: 'Always Ready', short: 'Always Ready', colors: ['#ffffff', '#d3222a'], league: 'bo-primera', size: 7, nickname: 'el Millonario' },
  { id: 'orientepetrolero', name: 'Oriente Petrolero', short: 'Oriente Petrolero', colors: ['#1a6b3c', '#ffffff'], league: 'bo-primera', size: 6, nickname: 'el Refinero' },
  { id: 'blooming', name: 'Blooming', short: 'Blooming', colors: ['#7ab8e6', '#ffffff'], league: 'bo-primera', size: 5, nickname: 'el Celeste' },
  { id: 'abb', name: 'Academia del Balompié Boliviano', short: 'ABB', colors: ['#f2c200', '#1a4fa0'], league: 'bo-primera', size: 5 },
  { id: 'aurora', name: 'Club Aurora', short: 'Aurora', colors: ['#7ab8e6', '#ffffff'], league: 'bo-primera', size: 4, nickname: 'el Equipo del Pueblo' },
  { id: 'guabira', name: 'Guabirá', short: 'Guabirá', colors: ['#d3222a', '#1a6b3c'], league: 'bo-primera', size: 4, nickname: 'la Furia Roja' },
  { id: 'nacionalpotosi', name: 'Nacional Potosí', short: 'Nacional Potosí', colors: ['#ffffff', '#d3222a'], league: 'bo-primera', size: 4, nickname: 'la Banda Roja' },
  { id: 'realpotosi', name: 'Real Potosí', short: 'Real Potosí', colors: ['#7b3f8b', '#ffffff'], league: 'bo-primera', size: 3, nickname: 'los Lilas' },
  { id: 'gvsanjose', name: 'Gualberto Villarroel San José', short: 'GV San José', colors: ['#ffffff', '#1a4fa0'], league: 'bo-primera', size: 3 },
  { id: 'independientepetrolero', name: 'Independiente Petrolero', short: 'Independiente Petrolero', colors: ['#d3222a', '#ffffff'], league: 'bo-primera', size: 3, nickname: 'el Inde' },
  { id: 'realtomayapo', name: 'Real Tomayapo', short: 'Real Tomayapo', colors: ['#1a6b3c', '#f2c200'], league: 'bo-primera', size: 3, nickname: 'el Verdolaga' },
  { id: 'totorareal', name: 'Totora Real Oruro', short: 'Totora Real', colors: ['#7b1f2b', '#f2c200'], league: 'bo-primera', size: 2, nickname: 'el Rojo Carmesí' },
  { id: 'universitariovinto', name: 'Universitario de Vinto', short: 'U. de Vinto', colors: ['#7b1f2b', '#000000'], league: 'bo-primera', size: 2, nickname: 'el Manzanero' },
  { id: 'bulobulo', name: 'San Antonio Bulo Bulo', short: 'Bulo Bulo', colors: ['#7ab8e6', '#ffffff'], league: 'bo-primera', size: 2, nickname: 'el Santo' },
  { id: 'wilstermann', name: 'Jorge Wilstermann', short: 'Wilstermann', colors: ['#d3222a', '#1a4fa0'], league: 'bo-segunda', size: 3, nickname: 'el Aviador' },
  { id: 'universitariosucre', name: 'Universitario de Sucre', short: 'U. de Sucre', colors: ['#d3222a', '#1a4fa0'], league: 'bo-segunda', size: 3, nickname: 'el Docto' },
  { id: 'royalpari', name: 'Royal Pari', short: 'Royal Pari', colors: ['#d3222a', '#ffffff'], league: 'bo-segunda', size: 2, nickname: 'los Guerreros de Kalamai' },
  { id: 'realsantacruz', name: 'Real Santa Cruz', short: 'Real Santa Cruz', colors: ['#ffffff', '#d3222a'], league: 'bo-segunda', size: 2, nickname: 'el León Blanco del Pajonal' },
  { id: 'sanjuanfc', name: 'Integración del Norte San Juan', short: 'San Juan FC', colors: ['#1a6b3c', '#d9782d'], league: 'bo-segunda', size: 2 },
  { id: 'destroyers', name: 'Club Destroyers', short: 'Destroyers', colors: ['#f2c200', '#000000'], league: 'bo-segunda', size: 2, nickname: 'la Máquina Vieja' },
  { id: 'fancesa', name: 'Academia Deportiva Fancesa', short: 'Fancesa', colors: ['#d3222a', '#000000'], league: 'bo-segunda', size: 1, nickname: 'los Cementeros' },
  { id: 'mariscalbraun', name: 'Mariscal Braun', short: 'Mariscal Braun', colors: ['#ffffff', '#000000'], league: 'bo-segunda', size: 1, nickname: 'los Cerveceros' },
  { id: 'litoral', name: 'Deportivo Litoral', short: 'Litoral', colors: ['#d3222a', '#1a6b3c'], league: 'bo-segunda', size: 1, nickname: 'el Tricolor' },
  { id: 'barcelonasc', name: 'Barcelona SC', short: 'Barcelona SC', colors: ['#f2c200', '#d3222a'], league: 'ec-primera', size: 9, nickname: 'el Ídolo' },
  { id: 'emelec', name: 'Emelec', short: 'Emelec', colors: ['#1a4fa0', '#ffffff'], league: 'ec-primera', size: 9, nickname: 'el Bombillo' },
  { id: 'ldu', name: 'LDU Quito', short: 'LDU Quito', colors: ['#ffffff', '#7ab8e6'], league: 'ec-primera', size: 8, nickname: 'el Rey de Copas' },
  { id: 'independientedelvalle', name: 'Independiente del Valle', short: 'IDV', colors: ['#000000', '#1a4fa0'], league: 'ec-primera', size: 7, nickname: 'los Negriazules' },
  { id: 'ucatolicaec', name: 'Universidad Católica', short: 'U. Católica (Ec)', colors: ['#1a4fa0', '#7ab8e6'], league: 'ec-primera', size: 5, nickname: 'el Trencito Azul' },
  { id: 'aucas', name: 'Aucas', short: 'Aucas', colors: ['#d3222a', '#f2c200'], league: 'ec-primera', size: 5, nickname: 'los Papás' },
  { id: 'macara', name: 'Macará', short: 'Macará', colors: ['#7ab8e6', '#1a4fa0'], league: 'ec-primera', size: 4, nickname: 'el Ídolo Ambateño' },
  { id: 'depcuenca', name: 'Deportivo Cuenca', short: 'Dep. Cuenca', colors: ['#d3222a', '#000000'], league: 'ec-primera', size: 4 },
  { id: 'delfin', name: 'Delfín SC', short: 'Delfín', colors: ['#1a4fa0', '#f2c200'], league: 'ec-primera', size: 4, nickname: 'el Cetáceo' },
  { id: 'orense', name: 'Orense SC', short: 'Orense', colors: ['#1a6b3c', '#ffffff'], league: 'ec-primera', size: 3, nickname: 'el Vendaval Verde' },
  { id: 'mantafc', name: 'Manta FC', short: 'Manta FC', colors: ['#7ab8e6', '#ffffff'], league: 'ec-primera', size: 3, nickname: 'los Atuneros' },
  { id: 'tecnicouniversitario', name: 'Técnico Universitario', short: 'Técnico U.', colors: ['#d3222a', '#ffffff'], league: 'ec-primera', size: 3, nickname: 'el Rodillo Rojo' },
  { id: 'mushucruna', name: 'Mushuc Runa', short: 'Mushuc Runa', colors: ['#7b1f2b', '#1a6b3c'], league: 'ec-primera', size: 3, nickname: 'el Ponchito' },
  { id: 'guayaquilcity', name: 'Guayaquil City FC', short: 'Guayaquil City', colors: ['#7ab8e6', '#ffffff'], league: 'ec-primera', size: 2, nickname: 'los Ciudadanos' },
  { id: 'libertadloja', name: 'Libertad FC', short: 'Libertad (Loja)', colors: ['#d9782d', '#000000'], league: 'ec-primera', size: 2 },
  { id: 'leonesfc', name: 'Leones FC', short: 'Leones FC', colors: ['#d3222a', '#000000'], league: 'ec-primera', size: 2, nickname: 'la Manada' },
  { id: 'elnacional', name: 'El Nacional', short: 'El Nacional', colors: ['#d3222a', '#1a4fa0'], league: 'ec-segunda', size: 3, nickname: 'los Criollos' },
  { id: 'vinotinto', name: 'Atlético Vinotinto', short: 'Vinotinto', colors: ['#7b1f2b', '#ffffff'], league: 'ec-segunda', size: 2 },
  { id: 'nuevedeoctubre', name: '9 de Octubre FC', short: '9 de Octubre', colors: ['#7ab8e6', '#ffffff'], league: 'ec-segunda', size: 2, nickname: 'los Octubrinos' },
  { id: 'cumbaya', name: 'Cumbayá FC', short: 'Cumbayá', colors: ['#f2c200', '#000000'], league: 'ec-segunda', size: 2, nickname: 'los Parroquianos' },
  { id: 'cuencajuniors', name: 'Cuenca Juniors', short: 'Cuenca Juniors', colors: ['#1a6b3c', '#ffffff'], league: 'ec-segunda', size: 1 },
  { id: 'ligaportoviejo', name: 'Liga de Portoviejo', short: 'Liga Portoviejo', colors: ['#ffffff', '#d3222a'], league: 'ec-segunda', size: 1 },
  { id: 'atleticorojiblanco', name: 'Atlético Rojiblanco', short: 'At. Rojiblanco', colors: ['#d3222a', '#ffffff'], league: 'ec-segunda', size: 1 },
  { id: 'gualaceo', name: 'Gualaceo SC', short: 'Gualaceo', colors: ['#1a4fa0', '#ffffff'], league: 'ec-segunda', size: 1 },
  { id: 'independientejuniors', name: 'Independiente Juniors', short: 'Ind. Juniors', colors: ['#000000', '#1a4fa0'], league: 'ec-segunda', size: 1 },
  { id: 'sanantoniofc', name: 'San Antonio FC', short: 'San Antonio', colors: ['#ffffff', '#000000'], league: 'ec-segunda', size: 1 },
  { id: 'santodomingo', name: 'Santo Domingo', short: 'Santo Domingo', colors: ['#1a6b3c', '#f2c200'], league: 'ec-segunda', size: 1 },
  { id: 'veintidosdejulio', name: '22 de Julio', short: '22 de Julio', colors: ['#d3222a', '#000000'], league: 'ec-segunda', size: 1 },
];

export const CLUBS_BY_ID: Record<string, Club> = Object.fromEntries(
  CLUBS.map((club) => [club.id, club]),
);

export function getClub(id: string): Club {
  const club = CLUBS_BY_ID[id];
  if (!club) throw new Error(`Club desconocido: ${id}`);
  return club;
}
