import type { Club } from '@/lib/engine/types';

export const CLUBS: Club[] = [
  { id: 'boca', name: 'Boca Juniors', short: 'Boca', colors: ['#0a3a8c', '#f2c200'], league: 'ar-primera', size: 10, nickname: 'el Xeneize' },
  { id: 'river', name: 'River Plate', short: 'River', colors: ['#ffffff', '#d81e3f'], league: 'ar-primera', size: 10, nickname: 'el Millonario' },
  { id: 'racing', name: 'Racing Club', short: 'Racing', colors: ['#7ab8e6', '#ffffff'], league: 'ar-primera', size: 9, nickname: 'la Academia' },
  { id: 'independiente', name: 'Independiente', short: 'Independiente', colors: ['#d32f2f', '#ffffff'], league: 'ar-primera', size: 9, nickname: 'el Rojo' },
  { id: 'sanlorenzo', name: 'San Lorenzo', short: 'San Lorenzo', colors: ['#1b3f8b', '#c8102e'], league: 'ar-primera', size: 8, nickname: 'el Ciclón' },
  { id: 'velez', name: 'Vélez Sarsfield', short: 'Vélez', colors: ['#ffffff', '#0a4ea3'], league: 'ar-primera', size: 8, nickname: 'el Fortín' },
  { id: 'estudiantes', name: 'Estudiantes de La Plata', short: 'Estudiantes', colors: ['#e01e2b', '#ffffff'], league: 'ar-primera', size: 7, nickname: 'el Pincha' },
  { id: 'central', name: 'Rosario Central', short: 'Central', colors: ['#1a4fa0', '#f2c200'], league: 'ar-primera', size: 7, nickname: 'el Canalla' },
  { id: 'newells', name: "Newell's Old Boys", short: "Newell's", colors: ['#d3222a', '#000000'], league: 'ar-primera', size: 7, nickname: 'la Lepra' },
  { id: 'talleres', name: 'Talleres', short: 'Talleres', colors: ['#1b4fa0', '#ffffff'], league: 'ar-primera', size: 7, nickname: 'la T' },
  { id: 'belgrano', name: 'Belgrano', short: 'Belgrano', colors: ['#7ab8e6', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Pirata' },
  { id: 'lanus', name: 'Lanús', short: 'Lanús', colors: ['#7b1f2b', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Granate' },
  { id: 'huracan', name: 'Huracán', short: 'Huracán', colors: ['#ffffff', '#d81e3f'], league: 'ar-primera', size: 6, nickname: 'el Globo' },
  { id: 'argentinos', name: 'Argentinos Juniors', short: 'Argentinos', colors: ['#d81e3f', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Bicho' },
  { id: 'gimnasia', name: 'Gimnasia y Esgrima La Plata', short: 'Gimnasia', colors: ['#1d5fa8', '#ffffff'], league: 'ar-primera', size: 6, nickname: 'el Lobo' },
  { id: 'colon', name: 'Colón', short: 'Colón', colors: ['#d3222a', '#000000'], league: 'ar-primera', size: 6, nickname: 'el Sabalero' },
  { id: 'banfield', name: 'Banfield', short: 'Banfield', colors: ['#1a6b3c', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Taladro' },
  { id: 'defensa', name: 'Defensa y Justicia', short: 'Defensa', colors: ['#f2c200', '#1a6b3c'], league: 'ar-primera', size: 5, nickname: 'el Halcón' },
  { id: 'godoycruz', name: 'Godoy Cruz', short: 'Godoy Cruz', colors: ['#1a4fa0', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Tomba' },
  { id: 'instituto', name: 'Instituto', short: 'Instituto', colors: ['#d3222a', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'la Gloria' },
  { id: 'union', name: 'Unión', short: 'Unión', colors: ['#d3222a', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Tatengue' },
  { id: 'atltucuman', name: 'Atlético Tucumán', short: 'Atl. Tucumán', colors: ['#7ab8e6', '#ffffff'], league: 'ar-primera', size: 5, nickname: 'el Decano' },
  { id: 'tigre', name: 'Tigre', short: 'Tigre', colors: ['#1a4fa0', '#d81e3f'], league: 'ar-primera', size: 4, nickname: 'el Matador' },
  { id: 'sarmiento', name: 'Sarmiento', short: 'Sarmiento', colors: ['#1a6b3c', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'el Verde' },
  { id: 'platense', name: 'Platense', short: 'Platense', colors: ['#7b3f1f', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'el Calamar' },
  { id: 'centralcordoba', name: 'Central Córdoba', short: 'C. Córdoba', colors: ['#000000', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'el Ferroviario' },
  { id: 'indriv', name: 'Independiente Rivadavia', short: 'Ind. Rivadavia', colors: ['#1a4fa0', '#ffffff'], league: 'ar-primera', size: 4, nickname: 'la Lepra mendocina' },
  { id: 'aldosivi', name: 'Aldosivi', short: 'Aldosivi', colors: ['#f2c200', '#1a6b3c'], league: 'ar-primera', size: 3, nickname: 'el Tiburón' },
  { id: 'barracas', name: 'Barracas Central', short: 'Barracas', colors: ['#d3222a', '#ffffff'], league: 'ar-primera', size: 3, nickname: 'el Guapo' },
  { id: 'riestra', name: 'Deportivo Riestra', short: 'Riestra', colors: ['#000000', '#f2c200'], league: 'ar-primera', size: 3, nickname: 'el Blanquinegro' },

  { id: 'quilmes', name: 'Quilmes', short: 'Quilmes', colors: ['#ffffff', '#1a4fa0'], league: 'ar-nacional', size: 6, nickname: 'el Cervecero' },
  { id: 'ferro', name: 'Ferro Carril Oeste', short: 'Ferro', colors: ['#1a6b3c', '#ffffff'], league: 'ar-nacional', size: 5, nickname: 'el Verdolaga' },
  { id: 'chacarita', name: 'Chacarita Juniors', short: 'Chacarita', colors: ['#d3222a', '#000000'], league: 'ar-nacional', size: 5, nickname: 'el Funebrero' },
  { id: 'sanmartint', name: 'San Martín de Tucumán', short: 'San Martín (T)', colors: ['#d3222a', '#ffffff'], league: 'ar-nacional', size: 5, nickname: 'el Santo' },
  { id: 'atlanta', name: 'Atlanta', short: 'Atlanta', colors: ['#f2c200', '#1a4fa0'], league: 'ar-nacional', size: 4, nickname: 'el Bohemio' },
  { id: 'allboys', name: 'All Boys', short: 'All Boys', colors: ['#ffffff', '#000000'], league: 'ar-nacional', size: 4, nickname: 'el Albo' },
  { id: 'chicago', name: 'Nueva Chicago', short: 'Chicago', colors: ['#1a6b3c', '#000000'], league: 'ar-nacional', size: 4, nickname: 'el Torito' },
  { id: 'almagro', name: 'Almagro', short: 'Almagro', colors: ['#1a4fa0', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Tricolor' },
  { id: 'temperley', name: 'Temperley', short: 'Temperley', colors: ['#7ab8e6', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Gasolero' },
  { id: 'moron', name: 'Deportivo Morón', short: 'Morón', colors: ['#d3222a', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Gallo' },
  { id: 'gimnasiam', name: 'Gimnasia y Esgrima de Mendoza', short: 'Gimnasia (M)', colors: ['#ffffff', '#1a4fa0'], league: 'ar-nacional', size: 4, nickname: 'el Lobo mendocino' },
  { id: 'santelmo', name: 'San Telmo', short: 'San Telmo', colors: ['#1a4fa0', '#f2c200'], league: 'ar-nacional', size: 2, nickname: 'el Candombero' },
  { id: 'defbelgrano', name: 'Defensores de Belgrano', short: 'Defensores', colors: ['#d3222a', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'el Dragón' },
  { id: 'racingcba', name: 'Racing de Córdoba', short: 'Racing (C)', colors: ['#7ab8e6', '#ffffff'], league: 'ar-nacional', size: 3, nickname: 'la Academia cordobesa' },
  { id: 'estudiantesrc', name: 'Estudiantes de Río Cuarto', short: 'Estudiantes (RC)', colors: ['#1a6b3c', '#ffffff'], league: 'ar-nacional', size: 3 },
  { id: 'agropecuario', name: 'Agropecuario', short: 'Agropecuario', colors: ['#1a6b3c', '#ffffff'], league: 'ar-nacional', size: 2, nickname: 'el Sojero' },
  { id: 'guemes', name: 'Güemes', short: 'Güemes', colors: ['#000000', '#ffffff'], league: 'ar-nacional', size: 2, nickname: 'el Gaucho' },
  { id: 'mitre', name: 'Mitre', short: 'Mitre', colors: ['#f2c200', '#000000'], league: 'ar-nacional', size: 2, nickname: 'el Aurinegro' },

  { id: 'losandes', name: 'Los Andes', short: 'Los Andes', colors: ['#d3222a', '#ffffff'], league: 'ar-b', size: 3, nickname: 'el Milrayitas' },
  { id: 'colegiales', name: 'Colegiales', short: 'Colegiales', colors: ['#ffffff', '#000000'], league: 'ar-b', size: 2, nickname: 'el Tricolor de Munro' },
  { id: 'acassuso', name: 'Acassuso', short: 'Acassuso', colors: ['#d3222a', '#1a4fa0'], league: 'ar-b', size: 1, nickname: 'el Quemero de Boulogne' },
  { id: 'comunicaciones', name: 'Comunicaciones', short: 'Comunicaciones', colors: ['#1a6b3c', '#ffffff'], league: 'ar-b', size: 2, nickname: 'el Cartero' },
  { id: 'tallerresre', name: 'Talleres de Remedios de Escalada', short: 'Talleres (RE)', colors: ['#d3222a', '#ffffff'], league: 'ar-b', size: 2, nickname: 'el Albirrojo' },
  { id: 'canuelas', name: 'Cañuelas', short: 'Cañuelas', colors: ['#7b1f2b', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Tambero' },
  { id: 'docksud', name: 'Sportivo Dock Sud', short: 'Dock Sud', colors: ['#1a4fa0', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Docke' },
  { id: 'fenix', name: 'Fénix', short: 'Fénix', colors: ['#7b3f8b', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Ave' },
  { id: 'sanmiguel', name: 'San Miguel', short: 'San Miguel', colors: ['#f2c200', '#d3222a'], league: 'ar-b', size: 2, nickname: 'el Trueno Verde' },
  { id: 'excursionistas', name: 'Excursionistas', short: 'Excursionistas', colors: ['#ffffff', '#1a4fa0'], league: 'ar-b', size: 2, nickname: 'el Villero' },
  { id: 'uaiurquiza', name: 'UAI Urquiza', short: 'UAI Urquiza', colors: ['#1a6b3c', '#ffffff'], league: 'ar-b', size: 1 },
  { id: 'armenio', name: 'Deportivo Armenio', short: 'Armenio', colors: ['#d3222a', '#1a4fa0'], league: 'ar-b', size: 1, nickname: 'el Tricolor' },
  { id: 'italiano', name: 'Sportivo Italiano', short: 'Italiano', colors: ['#1a4fa0', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Tano' },
  { id: 'espanol', name: 'Deportivo Español', short: 'Español', colors: ['#d3222a', '#f2c200'], league: 'ar-b', size: 2, nickname: 'el Gallego' },
  { id: 'argentinoq', name: 'Argentino de Quilmes', short: 'Argentino (Q)', colors: ['#1a6b3c', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Mate' },
  { id: 'ituzaingo', name: 'Ituzaingó', short: 'Ituzaingó', colors: ['#1a4fa0', '#ffffff'], league: 'ar-b', size: 1, nickname: 'el Verde' },

  { id: 'penarol', name: 'Peñarol', short: 'Peñarol', colors: ['#000000', '#f2c200'], league: 'uy-primera', size: 8, nickname: 'el Carbonero' },
  { id: 'nacional', name: 'Nacional', short: 'Nacional', colors: ['#ffffff', '#1a4fa0'], league: 'uy-primera', size: 8, nickname: 'el Bolso' },
  { id: 'danubio', name: 'Danubio', short: 'Danubio', colors: ['#ffffff', '#000000'], league: 'uy-primera', size: 7, nickname: 'la Franja' },
  { id: 'defensor', name: 'Defensor Sporting', short: 'Defensor', colors: ['#7b3f8b', '#ffffff'], league: 'uy-primera', size: 7, nickname: 'el Violeta' },
  { id: 'liverpool', name: 'Liverpool', short: 'Liverpool', colors: ['#000000', '#1a4fa0'], league: 'uy-primera', size: 6, nickname: 'el Negriazul' },
  { id: 'wanderers', name: 'Montevideo Wanderers', short: 'Wanderers', colors: ['#000000', '#ffffff'], league: 'uy-primera', size: 6, nickname: 'el Bohemio' },
  { id: 'racinguy', name: 'Racing', short: 'Racing (Uy)', colors: ['#1a6b3c', '#ffffff'], league: 'uy-primera', size: 6, nickname: 'el Cervecero' },
  { id: 'progreso', name: 'Progreso', short: 'Progreso', colors: ['#f2c200', '#d3222a'], league: 'uy-primera', size: 5, nickname: 'el Gaucho' },
  { id: 'cerro', name: 'Cerro', short: 'Cerro', colors: ['#ffffff', '#7ab8e6'], league: 'uy-primera', size: 5, nickname: 'el Villero' },
  { id: 'bostonriver', name: 'Boston River', short: 'Boston River', colors: ['#1a6b3c', '#d3222a'], league: 'uy-primera', size: 5, nickname: 'el Sastre' },
  { id: 'cerrolargo', name: 'Cerro Largo', short: 'Cerro Largo', colors: ['#1a4fa0', '#ffffff'], league: 'uy-primera', size: 4, nickname: 'el Arachán' },
  { id: 'maldonado', name: 'Deportivo Maldonado', short: 'Maldonado', colors: ['#d3222a', '#1a6b3c'], league: 'uy-primera', size: 4, nickname: 'el Depo' },
  { id: 'citytorque', name: 'Montevideo City Torque', short: 'City Torque', colors: ['#7ab8e6', '#ffffff'], league: 'uy-primera', size: 4, nickname: 'el Ciudadano' },
  { id: 'centralespanol', name: 'Central Español', short: 'Central Español', colors: ['#d3222a', '#1a4fa0'], league: 'uy-primera', size: 4, nickname: 'el Palermitano' },
  { id: 'albion', name: 'Albion', short: 'Albion', colors: ['#d3222a', '#0a3a8c'], league: 'uy-primera', size: 3, nickname: 'el Decano' },
  { id: 'juventud', name: 'Juventud', short: 'Juventud', colors: ['#1a4fa0', '#ffffff'], league: 'uy-primera', size: 3, nickname: 'el Canario' },

  { id: 'riverplateuy', name: 'River Plate', short: 'River Plate (Uy)', colors: ['#d3222a', '#ffffff'], league: 'uy-segunda', size: 2, nickname: 'el Darsenero' },
  { id: 'rentistas', name: 'Rentistas', short: 'Rentistas', colors: ['#d3222a', '#000000'], league: 'uy-segunda', size: 2, nickname: 'el Bicho' },
  { id: 'miramar', name: 'Miramar Misiones', short: 'Miramar', colors: ['#000000', '#ffffff'], league: 'uy-segunda', size: 2, nickname: 'el Cebra' },
  { id: 'plazacolonia', name: 'Plaza Colonia', short: 'Plaza Colonia', colors: ['#ffffff', '#1a6b3c'], league: 'uy-segunda', size: 2, nickname: 'las Patas Blancas' },
  { id: 'tacuarembo', name: 'Tacuarembó', short: 'Tacuarembó', colors: ['#7b1f2b', '#ffffff'], league: 'uy-segunda', size: 2, nickname: 'el Tacua' },
  { id: 'huracanuy', name: 'Huracán', short: 'Huracán (Uy)', colors: ['#1a4fa0', '#ffffff'], league: 'uy-segunda', size: 1, nickname: 'el Hura' },
  { id: 'paysandu', name: 'Paysandú', short: 'Paysandú', colors: ['#ffffff', '#1a4fa0'], league: 'uy-segunda', size: 2, nickname: 'el Paysa' },
  { id: 'colonuy', name: 'Colón', short: 'Colón (Uy)', colors: ['#1a6b3c', '#d3222a'], league: 'uy-segunda', size: 1, nickname: 'el Verde' },
  { id: 'cerrito', name: 'Cerrito', short: 'Cerrito', colors: ['#f2c200', '#1a6b3c'], league: 'uy-segunda', size: 1, nickname: 'el Auriverde' },
  { id: 'umontevideo', name: 'Uruguay Montevideo', short: 'Uruguay MVD', colors: ['#7ab8e6', '#000000'], league: 'uy-segunda', size: 1, nickname: 'la Celestina' },
  { id: 'atenas', name: 'Atenas', short: 'Atenas', colors: ['#1a4fa0', '#d3222a'], league: 'uy-segunda', size: 1, nickname: 'el Azulgrana' },
  { id: 'oriental', name: 'Oriental', short: 'Oriental', colors: ['#7ab8e6', '#ffffff'], league: 'uy-segunda', size: 1, nickname: 'el Paceño' },
  { id: 'laluz', name: 'La Luz', short: 'La Luz', colors: ['#1a6b3c', '#ffffff'], league: 'uy-segunda', size: 1, nickname: 'el Merengue' },

  { id: 'alianzalima', name: 'Alianza Lima', short: 'Alianza Lima', colors: ['#0a3a8c', '#ffffff'], league: 'pe-primera', size: 9, nickname: 'el Íntimo' },
  { id: 'universitario', name: 'Universitario de Deportes', short: 'Universitario', colors: ['#e8d9a8', '#7b1f2b'], league: 'pe-primera', size: 9, nickname: 'la U' },
  { id: 'sportingcristal', name: 'Sporting Cristal', short: 'Cristal', colors: ['#7ab8e6', '#ffffff'], league: 'pe-primera', size: 9, nickname: 'el Cervecero' },
  { id: 'melgar', name: 'FBC Melgar', short: 'Melgar', colors: ['#d3222a', '#000000'], league: 'pe-primera', size: 7, nickname: 'el Dominó' },
  { id: 'cienciano', name: 'Cienciano', short: 'Cienciano', colors: ['#d3222a', '#ffffff'], league: 'pe-primera', size: 7, nickname: 'el Papá' },
  { id: 'sportboys', name: 'Sport Boys', short: 'Sport Boys', colors: ['#e88fb3', '#1a4fa0'], league: 'pe-primera', size: 6, nickname: 'la Misilera' },
  { id: 'cuscofc', name: 'Cusco FC', short: 'Cusco FC', colors: ['#c9a227', '#000000'], league: 'pe-primera', size: 6, nickname: 'el Dorado' },
  { id: 'garcilaso', name: 'Deportivo Garcilaso', short: 'Garcilaso', colors: ['#7ab8e6', '#ffffff'], league: 'pe-primera', size: 5, nickname: 'la G' },
  { id: 'sporthuancayo', name: 'Sport Huancayo', short: 'Sport Huancayo', colors: ['#d3222a', '#ffffff'], league: 'pe-primera', size: 5, nickname: 'el Rojo Matador' },
  { id: 'adt', name: 'ADT', short: 'ADT', colors: ['#7ab8e6', '#ffffff'], league: 'pe-primera', size: 5, nickname: 'el Vendaval Celeste' },
  { id: 'alianzaatletico', name: 'Alianza Atlético', short: 'Alianza Atlético', colors: ['#ffffff', '#1a4fa0'], league: 'pe-primera', size: 4, nickname: 'Alianza de Oro' },
  { id: 'atleticograu', name: 'Atlético Grau', short: 'Grau', colors: ['#ffffff', '#d3222a'], league: 'pe-primera', size: 4, nickname: 'los Albos' },
  { id: 'comerciantesunidos', name: 'Comerciantes Unidos', short: 'Comerciantes Unidos', colors: ['#7b3f8b', '#f2c200'], league: 'pe-primera', size: 4, nickname: 'las Águilas' },
  { id: 'utc', name: 'UTC', short: 'UTC', colors: ['#e8d9a8', '#5c3a21'], league: 'pe-primera', size: 4, nickname: 'el Gavilán' },
  { id: 'cajamarca', name: 'FC Cajamarca', short: 'Cajamarca', colors: ['#1a4fa0', '#f2c200'], league: 'pe-primera', size: 3 },
  { id: 'moquegua', name: 'Deportivo Moquegua', short: 'Moquegua', colors: ['#f2c200', '#000000'], league: 'pe-primera', size: 3 },
  { id: 'loschankas', name: 'Los Chankas', short: 'Los Chankas', colors: ['#7b1f2b', '#d9782d'], league: 'pe-primera', size: 3, nickname: 'los Guerreros' },
  { id: 'jpiicollege', name: 'Juan Pablo II College', short: 'JP II College', colors: ['#ffffff', '#f2c200'], league: 'pe-primera', size: 2 },

  { id: 'cantolao', name: 'Academia Cantolao', short: 'Cantolao', colors: ['#f2c200', '#000000'], league: 'pe-segunda', size: 2, nickname: 'el Delfín' },
  { id: 'adajaen', name: 'ADA Jaén', short: 'ADA Jaén', colors: ['#1a6b3c', '#f2c200'], league: 'pe-segunda', size: 1 },
  { id: 'alianzauniversidad', name: 'Alianza Universidad', short: 'Alianza Universidad', colors: ['#1a4fa0', '#d3222a'], league: 'pe-segunda', size: 3, nickname: 'la UDH' },
  { id: 'ayacucho', name: 'Ayacucho FC', short: 'Ayacucho FC', colors: ['#ffffff', '#d9782d'], league: 'pe-segunda', size: 3, nickname: 'los Zorros' },
  { id: 'tacnaheroica', name: 'Bentín Tacna Heroica', short: 'Tacna Heroica', colors: ['#1a4fa0', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'el Vendaval Azul' },
  { id: 'mannucci', name: 'Carlos A. Mannucci', short: 'Mannucci', colors: ['#0a3a8c', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'el Grifo' },
  { id: 'comerciantesfc', name: 'Comerciantes FC', short: 'Comerciantes FC', colors: ['#1a6b3c', '#ffffff'], league: 'pe-segunda', size: 1, nickname: 'la Fuerza' },
  { id: 'binacional', name: 'Deportivo Binacional', short: 'Binacional', colors: ['#7ab8e6', '#ffffff'], league: 'pe-segunda', size: 3, nickname: 'el Poderoso' },
  { id: 'llacuabamba', name: 'Deportivo Llacuabamba', short: 'Llacuabamba', colors: ['#ffffff', '#2fa89e'], league: 'pe-segunda', size: 1, nickname: 'los Mineros' },
  { id: 'cni', name: 'Estudiantil CNI', short: 'CNI', colors: ['#ffffff', '#1a6b3c'], league: 'pe-segunda', size: 1 },
  { id: 'piratafc', name: 'Pirata FC', short: 'Pirata FC', colors: ['#000000', '#1a6b3c'], league: 'pe-segunda', size: 2, nickname: 'los Piratas' },
  { id: 'santosnazca', name: 'Santos FC', short: 'Santos (Nazca)', colors: ['#1a4fa0', '#ffffff'], league: 'pe-segunda', size: 1, nickname: 'la Máquina' },
  { id: 'unioncomercio', name: 'Unión Comercio', short: 'Unión Comercio', colors: ['#d3222a', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'el Poderoso del Altomayo' },
  { id: 'unionminas', name: 'Unión Minas', short: 'Unión Minas', colors: ['#f2c200', '#1a4fa0'], league: 'pe-segunda', size: 1, nickname: 'el Rodillo Minero' },
  { id: 'ucv', name: 'Universidad César Vallejo', short: 'UCV', colors: ['#1a4fa0', '#ffffff'], league: 'pe-segunda', size: 2, nickname: 'los Poetas' },
  { id: 'usmp', name: 'Universidad San Martín', short: 'USMP', colors: ['#ffffff', '#0a3a8c'], league: 'pe-segunda', size: 2, nickname: 'el Sanmartinense' },
];

export const CLUBS_BY_ID: Record<string, Club> = Object.fromEntries(
  CLUBS.map((club) => [club.id, club]),
);

export function getClub(id: string): Club {
  const club = CLUBS_BY_ID[id];
  if (!club) throw new Error(`Club desconocido: ${id}`);
  return club;
}
