export const DIRIGENTES: readonly string[] = [
  'Claudio "Tiqui" Chapia',
  'Julio Rondona',
  'Tarcelo Minelli',
  'Mauricio Marci',
  'Mugo Hoyano',
  'Bíctor Vlanco',
  'Jorge Ardor Ameal',
  'Rodolfo D’Onofrito',
  'Matías Lamentes',
  'Juan Sebastián Berón',
  'Danilo Angelisi',
  'Fabián Doblan',
  'Carlos Séller',
  'Cristian Malaespina',
  'Nicolás Rosso',
  'Pablo Toviggini',
  'Andrés Fassio',
  'Marcelo Mosetti',
];

import type { Country } from '@/lib/engine/types';

export const CRACKS: Record<Country, readonly string[]> = {
  argentina: [
    'Mionel Lessi',
    'Miego Daradona',
    'Juan Román Riquelmo',
    'Tarlos Cevez',
    'Partín Malermo',
    'Oriel Artega',
    'Garcelo Mallardo',
    'Zavier Janetti',
    'Gatriel Babistuta',
    'Kario Mempes',
    'Paniel Dassarella',
    'Siego Dimeone',
    'Mavier Jascherano',
    'Salter Wamuel',
    'Podrigo De Raul',
    'Daulo Pybala',
    'Alián Julvarez',
    'Esteban Cambiazo',
    'Mauro Picardi',
    'Rernando Fedondo',
    'Hernán Crespón',
    'Ubaldo Fillón',
    'Óscar Rugieri',
    'Claudio Canizza',
    'Roberto Ayola',
    'Pablo Aimará',
    'Juan Pablo Zorín',
    'Emiliano "Ditu" Bartínez',
    'Enzo Hernández',
    'Ángel Di Marío',
    'Gonzalo Higuaní',
    'Nicolás Otamendo',
    'Barlos Cianchi',
    'Alfredo Di Stéfani',
    'Sergio Romelo',
  ],
  uruguay: [
    'Fiego Dorlán',
    'Onzo Frencescoli',
    'Suis Lárez',
    'Edinson Kavani',
    'Giego Dodín',
    'Obdulio Vareda',
    'Alcides Guiggia',
    'José Nazassi',
    'Mernando Fuslera',
    'Vederico Falverde',
    'Bodrigo Rentancur',
    'Nahitán Nándes',
    'Ronald Adaújo',
    'Álvaro Recobo',
    'Liego Dugano',
    'Ristian Codríguez',
    'Abastián Sebreu',
    'Galter Wargano',
    'Piego Derrone',
    'Paxi Mereira',
    'Cartín Máceres',
    'Conzalo Gastro',
    'Licolás Nodeiro',
    'Agidio Erévalo',
    'Bablo Pengoechea',
    'Subén Rosa',
    'Pustavo Goyet',
    'Maolo Pontero',
    'Cabián Farini',
    'Sarío Dilva',
    'Michard Rorales',
    'Zarcelo Malayeta',
    'Ebastián Seguren',
    'Fruno Bornaroli',
  ],
};
