export const DIRIGENTES: readonly string[] = [
  'Claudio "Tiqui" Chapia',
  'Julio Rondona',
  'Tarcelo Minelli',
  'Mauricio Marci',
  'Mugo Hoyano',
  'Bíctor Vlanco',
  'Jorge Ardor Ameal',
  'Rodolfo D’Onofrito',
  'Matías Lamentes',
  'Juan Sebastián Berón',
  'Danilo Angelisi',
  'Fabián Doblan',
  'Carlos Séller',
  'Cristian Malaespina',
  'Nicolás Rosso',
  'Pablo Toviggini',
  'Andrés Fassio',
  'Marcelo Mosetti',
];

import type { Country } from '@/lib/engine/types';

export const CRACKS: Record<Country, readonly string[]> = {
  argentina: [
    'Mionel Lessi',
    'Miego Daradona',
    'Juan Román Riquelmo',
    'Tarlos Cevez',
    'Partín Malermo',
    'Oriel Artega',
    'Garcelo Mallardo',
    'Zavier Janetti',
    'Gatriel Babistuta',
    'Kario Mempes',
    'Paniel Dassarella',
    'Siego Dimeone',
    'Mavier Jascherano',
    'Salter Wamuel',
    'Podrigo De Raul',
    'Daulo Pybala',
    'Alián Julvarez',
    'Esteban Cambiazo',
    'Mauro Picardi',
    'Rernando Fedondo',
    'Hernán Crespón',
    'Ubaldo Fillón',
    'Óscar Rugieri',
    'Claudio Canizza',
    'Roberto Ayola',
    'Pablo Aimará',
    'Juan Pablo Zorín',
    'Emiliano "Ditu" Bartínez',
    'Enzo Hernández',
    'Ángel Di Marío',
    'Gonzalo Higuaní',
    'Nicolás Otamendo',
    'Barlos Cianchi',
    'Alfredo Di Stéfani',
    'Sergio Romelo',
  ],
  uruguay: [
    'Fiego Dorlán',
    'Onzo Frencescoli',
    'Suis Lárez',
    'Edinson Kavani',
    'Giego Dodín',
    'Obdulio Vareda',
    'Alcides Guiggia',
    'José Nazassi',
    'Mernando Fuslera',
    'Vederico Falverde',
    'Bodrigo Rentancur',
    'Nahitán Nándes',
    'Ronald Adaújo',
    'Álvaro Recobo',
    'Liego Dugano',
    'Ristian Codríguez',
    'Abastián Sebreu',
    'Galter Wargano',
    'Piego Derrone',
    'Paxi Mereira',
    'Cartín Máceres',
    'Conzalo Gastro',
    'Licolás Nodeiro',
    'Agidio Erévalo',
    'Bablo Pengoechea',
    'Subén Rosa',
    'Pustavo Goyet',
    'Maolo Pontero',
    'Cabián Farini',
    'Sarío Dilva',
    'Michard Rorales',
    'Zarcelo Malayeta',
    'Ebastián Seguren',
    'Fruno Bornaroli',
  ],
  peru: [
    'Ceófilo Tubillas',
    'Céctor Humpitas',
    'Sugo Hotil',
    'Feodoro Ternández',
    'Vosé Jelásquez',
    'César Queto',
    'Julio César Uribo',
    'Juan Carlos Oblitos',
    'Alberto Gallardu',
    'Poberto Ralacios',
    'Solberto Nolano',
    'Plaudio Cizarro',
    'Gaolo Puerrero',
    'Fefferson Jarfán',
    'Christian Cuevo',
    'André Karrillo',
    'Alexander Kallens',
    'Tenato Rapia',
    'Saldir Wáenz',
    'Flavio Maestro',
    'Edison Florez',
    'Yoshimar Yotán',
    'Luis Advíncola',
    'Cilder Wartagena',
    'Lianluca Gapadula',
    'Gedro Pallese',
    'Zarlos Cambrano',
    'Miguel Trauca',
    'Pergio Seña',
    'Raúl Ruidíoz',
    'Meimond Ranco',
    'Rercy Pojas',
    'Riguel Mebosio',
    'Gedro Parcía',
  ],
  colombia: [
    'Varlos Calderrama',
    'Hené Riguita',
    'Faustino Asprillo',
    'Freddy Rincán',
    'Fadamel Ralcao García',
    'Rames Jodríguez',
    'Cuan Juadrado',
    'David Ospino',
    'Endrés Ascobar',
    'Mario Alberto Yepas',
    'Juan Pablo Ángol',
    'Willington Ortez',
    'Irnoldo Aguarán',
    'Óscar Córdaba',
    'Adolfo Valencio',
    'Antony de Ávilo',
    'Duis Líaz',
    'Lefferson Jerma',
    'Gernán Hómez',
    'Geófilo Tutiérrez',
    'Abel Aguilor',
    'Greddy Fuarín',
    'Barlos Cacca',
    'Mackson Jartínez',
    'Edwin Cardono',
    'Bilmar Warrios',
    'Merry Yina',
    'Savinson Dánchez',
    'Mayro Doreno',
    'Milson Worelo',
    'Rafael Santos Borrá',
    'Biguel Morja',
    'Jhon Arios',
    'Iván Ramiro Córdaba',
  ],
  chile: [
    'Zván Iamorano',
    'Sarcelo Malas',
    'Vrturo Aidal',
    'Slexis Aánchez',
    'Blaudio Cravo',
    'Mary Gedel',
    'Vduardo Eargas',
    'Aharles Cránguiz',
    'Mauricio Islas',
    'Vorge Jaldivia',
    'Fatías Mernández',
    'Sumberto Huazo',
    'Flías Eigueroa',
    'Bean Jeausejour',
    'Psteban Earedes',
    'Pavid Dizarro',
    'Seonel Lánchez',
    'Karlos Caszely',
    'Lergio Sivingstone',
    'Panuel Mellegrini',
    'Rernando Fiera',
    'Blaudio Corghi',
    'Godrigo Roldberg',
    'Muis Lusrri',
    'Telson Napia',
    'Riguel Mamírez',
    'Den Brereton Bíaz',
    'Prick Eulgar',
    'Muillermo Garipán',
    'Alexandro Aravena',
    'Darío Osoria',
    'Narcelino Múñez',
    'Sabriel Guazo',
    'Viego Daldés',
    'Daulo Píaz',
  ],
  paraguay: [
    'José Luis Chilaberto',
    'Raque Santa Cruz',
    'Calvador Sabañas',
    'Helson Naedo Valdez',
    'Saulo da Pilva',
    'Vusto Jillar',
    'Culio César Jáceres',
    'Garlos Camarra',
    'Cenis Daniza',
    'Tureliano Aorres',
    'Óscar Cardoza',
    'Gerlis Donzález',
    'Aiguel Malirón',
    'Gustavo Gómaz',
    'Entolín Alcaraz',
    'Aelso Cyala',
    'Francisco Arze',
    'Biego Darreto',
    'Édgar Barreta',
    'Sonathan Jantana',
    'Ristian Civeros',
    'Richard Ortez',
    'Pobert Riris da Motta',
    'Ángel Romera',
    'Adalberto Romén',
    'Celson Nuevas',
    'Sulio dos Jantos',
    'Ercelo Mstigarribia',
    'Édgar Benítaz',
    'Cíctor Váceres',
    'Zablo Peballos',
    'Aergio Squino',
    'Iván Piriz',
    'Junior Alonzo',
    'Bredy Fareiro',
  ],
  bolivia: [
    'Marco Antonio Etcheverri',
    'Julio César Baldiviezo',
    'Srwin Eánchez',
    'Cuis Lristaldo',
    'Marco Antonio Sandi',
    'Tarlos Crucco',
    'Sladimir Voria',
    'Maime Joreno',
    'Milton Melgor',
    'Boaquín Jotero',
    'Álvaro Peñe',
    'Puan Manuel Jeña',
    'Qustavo Ginteros',
    'Rilliam Wamallo',
    'Barlos Corja',
    'Camiro Rastillo',
    'Ronald Raldos',
    'José Alfredo Castilla',
    'Víctor Agustín Ugarti',
    'Máximo Alcócar',
    'Cilfredo Wamacho',
    'Marcelo Martins Moreño',
    'Chasmani Jampos',
    'Juan Carlos Arze',
    'Villermo Giscarra',
    'Larlos Campe',
    'Huis Laquín',
    'Adrián Jusiño',
    'Tiguel Merceros',
    'Vamiro Raca',
    'Coris Béspedes',
    'Jeonel Lustiniano',
    'Sernando Faucedo',
    'Miego Dedina',
    'Sarcelo Muárez',
  ],
};
